### ISSUE TITLE
todo for getting live to version 2019

### ISSUE THREAD

**Issue by mschaaf** [Dica-Developer/weplantaforest#104]
- [ ] get plant coordinates
- [ ] test live system DB upgrade from zero  
- [ ] update deploy scripts
- [ ] disable http mode
- [ ]

**Comment by mschaaf** [comment]
moved to project
